# Generated by Django 3.2.6 on 2021-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparableproperty',
            name='is_comparable',
            field=models.BooleanField(default=True),
        ),
    ]
