# Generated by Django 3.2.6 on 2021-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_comparableproperty_is_comparable'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparableproperty',
            name='correct_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
