# Generated by Django 3.2.6 on 2021-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211007_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparabletable',
            name='correction_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
