# Generated by Django 3.2.6 on 2021-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_comparabletable_correction_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparabletable',
            name='price_persqm',
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='name',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
