# Generated by Django 3.2.6 on 2021-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211007_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparableproperty',
            name='camara',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparableproperty',
            name='rent_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
