# Generated by Django 3.2.6 on 2021-10-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211008_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='conform',
            field=models.CharField(blank=True, choices=[('inspectiei', 'Inspectiei'), ('cpe', 'Certificatului de performanta energetica'), ('procesului', 'Procesului verbal de receptie la terminarea lucrarilor'), ('planului', 'Planului de amplasament si de mutare a imobilului')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='construction',
            name='invelitoare',
            field=models.CharField(blank=True, choices=[('bitum', 'Bitum'), ('tigla', 'Tigla'), ('tabla', 'Tabla')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentationdata',
            name='access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentationdata',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='valued_property',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='compartment',
            field=models.CharField(blank=True, choices=[('', 'Alege'), ('decomandat', 'Decomandat'), ('semidecomandat', 'Semidecomandat'), ('nedecomandat', 'Neecomandat'), ('circular', 'Circular')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='heating',
            field=models.CharField(blank=True, choices=[('termoficare', 'Termoficare'), ('ctp', 'Centrala termica proprie'), ('ctb', 'Centrala termica a blocului')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='closure',
            field=models.CharField(blank=True, choices=[('zc', 'Zidarie Caramida'), ('bca', 'Zidarie BCA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='foundation',
            field=models.CharField(blank=True, choices=[('armat', 'Continue din beton armat'), ('stalpi', 'Stalpi din beton armat prefabricat'), ('grinzi', 'Grinzi continue sub stalpi'), ('trg', 'Tip Radier General'), ('piloti', 'Pe piloti'), ('chesoane', 'Pe chesoane')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='heating',
            field=models.CharField(blank=True, choices=[('termoficare', 'Termoficare'), ('ctp', 'Centrala termica proprie'), ('ctb', 'Centrala termica a blocului')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='roof',
            field=models.CharField(blank=True, choices=[('tc', 'Terasa circulabila'), ('tn', 'Terasa necirculabila'), ('sl', 'Sarpanta din lemn'), ('sm', 'Sarpanta din metal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='structure',
            field=models.CharField(blank=True, choices=[('zp', 'Zidarie portanta'), ('armat', 'Cadre din beton armat'), ('metal', 'Cadre de metal'), ('darmat', 'Diafragme din beton armat'), ('lemn', 'Lemn'), ('mix', 'Mixt – cadre de metal + structura put beton')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='subcompartment',
            field=models.CharField(blank=True, choices=[('rigips', 'Rigips'), ('bca', 'BCA'), ('caramida', 'Caramida')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evaluareform',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('', 'Alege'), ('decomandat', 'Decomandat'), ('semidecomandat', 'Semidecomandat'), ('nedecomandat', 'Neecomandat'), ('circular', 'Circular')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='current_use',
            field=models.CharField(blank=True, choices=[('ldp', 'Locuit de proprietar'), ('liber', 'Liber'), ('ldc', 'Locuit de chirias')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='identification',
            field=models.CharField(blank=True, choices=[('apii', 'Adresei postale inscrise pe imobil'), ('cipa', 'Cadastral introdus pe platforma ANCPI')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='residentialattrvalue',
            name='floor_type',
            field=models.CharField(blank=True, choices=[('beton', 'Beton armat'), ('lemn', 'Lemn')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='valuationsummary',
            name='purpose',
            field=models.CharField(blank=True, choices=[('bank_guarantee', 'Garantare Bancara'), ('informativ', 'Informativ'), ('raportare_financiara', 'Raportare Financiara')], max_length=150, null=True),
        ),
    ]
