# Generated by Django 3.2.6 on 2021-10-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211011_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationsummary',
            name='boxa_iv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='boxa_mv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='subteran_iv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='subteran_mv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='suprateran_iv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='suprateran_mv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
