# Generated by Django 3.2.6 on 2021-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt1_name',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt1_val',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt2_name',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt2_val',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt3_name',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt3_val',
        ),
        migrations.AddField(
            model_name='comparableproperty',
            name='camara',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
