# Generated by Django 3.2.6 on 2021-10-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartimentare',
            name='has_nr',
        ),
        migrations.RemoveField(
            model_name='compartimentare',
            name='has_photo',
        ),
        migrations.RemoveField(
            model_name='presentationdata',
            name='description',
        ),
        migrations.AlterField(
            model_name='construction',
            name='invelitoare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valuation.invelitoaretype'),
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='approach',
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='approach',
            field=models.ManyToManyField(blank=True, to='valuation.ValuationApproach'),
        ),
    ]
