# Generated by Django 3.2.6 on 2021-11-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_auto_20211108_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparabletable',
            name='selected_comp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
