# Generated by Django 3.2.6 on 2021-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_auto_20211019_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartimentarevalue',
            name='iav',
        ),
        migrations.RemoveField(
            model_name='compartimentarevalue',
            name='mav',
        ),
        migrations.AddField(
            model_name='marketanalysis',
            name='ac_optional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
