# Generated by Django 3.2.6 on 2021-11-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_comparabletable_selected_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparabletable',
            name='selected_comp',
        ),
    ]
