# Generated by Django 3.2.6 on 2021-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0004_auto_20211020_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparableproperty',
            name='finish',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='hs',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='mobila',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='pr',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='const_density',
            field=models.CharField(blank=True, choices=[('mare', 'mare'), ('medie', 'medie')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='exposure_period',
            field=models.CharField(blank=True, choices=[('scurte', 'scurte'), ('lungi', 'lungi')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='liquidity',
            field=models.CharField(blank=True, choices=[('buna', 'buna'), ('medie', 'medie'), ('slaba', 'slaba')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='prop_size',
            field=models.CharField(blank=True, choices=[('medie', 'medie'), ('mare', 'mare'), ('mica', 'mica')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='transactions_nr',
            field=models.CharField(blank=True, choices=[('mediu', 'mediu'), ('mare', 'mare'), ('redus', 'redus')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='zona_type',
            field=models.CharField(blank=True, choices=[('medii', 'medii'), ('sub medie', 'sau sub medie'), ('above average', 'de vârstă medie/medii sau peste medie'), ('medium age', 'de varsta medie')], max_length=155, null=True),
        ),
    ]
