# Generated by Django 3.2.6 on 2021-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0005_auto_20211020_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparableproperty',
            name='ad',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='ape',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='cp',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='fc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='sc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
