# Generated by Django 3.2.6 on 2021-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0007_auto_20211020_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparableproperty',
            name='opt1_val',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='opt2_val',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='opt3_val',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
