# Generated by Django 3.2.6 on 2021-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0008_auto_20211020_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparableproperty',
            name='price_persqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
