# Generated by Django 3.2.6 on 2021-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0009_auto_20211110_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparabletable',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='comparabletable',
            name='smallest_gross',
        ),
        migrations.AddField(
            model_name='comparableproperty',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparableproperty',
            name='smallest_gross',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='opt1_val',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='opt2_val',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparableproperty',
            name='opt3_val',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparabletable',
            name='opt1_val',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparabletable',
            name='opt2_val',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparabletable',
            name='opt3_val',
            field=models.TextField(blank=True, null=True),
        ),
    ]
