# Generated by Django 3.2.6 on 2021-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0010_auto_20211021_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartimentarevalue',
            name='floor_type',
        ),
        migrations.AddField(
            model_name='construction',
            name='floors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
