# Generated by Django 3.2.6 on 2021-11-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0010_auto_20211110_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparabletable',
            old_name='comparabl',
            new_name='comparable',
        ),
    ]
