# Generated by Django 3.2.6 on 2021-11-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0011_rename_comparabl_comparabletable_comparable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvbtable',
            name='cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valuation.comparableproperty'),
        ),
    ]
