# Generated by Django 3.2.6 on 2021-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0012_mvbtable_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationdata',
            name='access_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentationdata',
            name='cadastral_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
