# Generated by Django 3.2.6 on 2021-10-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0013_auto_20211022_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='suprafete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='ef_choice',
            field=models.CharField(blank=True, choices=[('medii', 'medii'), ('bune', 'bune')], max_length=55, null=True),
        ),
    ]
