# Generated by Django 3.2.6 on 2021-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0013_auto_20211115_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparableproperty',
            name='ape_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='balcon_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='cp_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='cy_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='etaj_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='fc_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='finish_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='hs_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='lc_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='me_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt1_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt1_name',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt1_val',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt2_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt2_name',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt2_val',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt3_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt3_name',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='opt3_val',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='pr_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='price_persqm',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='sc_motivation',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='smallest_gross',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='su_motivation',
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='ad',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='ape',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='ape_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='balcon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='balcon_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='cp',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='cp_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='cy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='cy_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='etaj',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='etaj_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='fc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='fc_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='finish',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='finish_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='hs',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='hs_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='lc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='lc_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='ma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='me',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='me_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='mobila',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt1_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt1_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt2_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt2_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt3_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='opt3_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='parking_boxa',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='pba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='pr',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='pr_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='price_persqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sc_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='smallest_gross',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='su_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_ad',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_ape',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_balcon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_cp',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_cy',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_etaj',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_fc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_finish',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_hs',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_lc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_me',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_opt1',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_opt2',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_opt3',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_pr',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='sub_sc',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='building_no',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='floor_no',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='zona',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comparabletable',
            name='opt1_val',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='comparabletable',
            name='opt2_val',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='application_similar',
            field=models.CharField(blank=True, choices=[('echilibru', 'In echilibru'), ('scadere', 'In scadere'), ('crestere', 'In crestere')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='market_balance',
            field=models.CharField(blank=True, choices=[('echilibru', 'In echilibru'), ('scadere', 'In scadere'), ('crestere', 'In crestere')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='offer_similar',
            field=models.CharField(blank=True, choices=[('echilibru', 'In echilibru'), ('scadere', 'In scadere'), ('crestere', 'In crestere')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='zona_type',
            field=models.CharField(blank=True, choices=[('medii', 'medii'), ('sub medie', 'sau sub medie'), ('above average', 'de varsta medie/medii sau peste medie'), ('medium age', 'de varsta medie')], max_length=155, null=True),
        ),
    ]
