# Generated by Django 3.2.6 on 2021-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0014_auto_20211116_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuatedproperty',
            name='address',
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='numarul',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='postal_code',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='valuatedproperty',
            name='scara',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
