# Generated by Django 3.2.6 on 2021-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0014_auto_20211022_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='suprafete',
            name='nr_crt',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='suprafete',
            name='totala',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suprafete',
            name='utila',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
