# Generated by Django 3.2.6 on 2021-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0015_auto_20211116_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationdata',
            name='access_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
