# Generated by Django 3.2.6 on 2021-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0015_auto_20211022_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suprafete',
            name='totala',
        ),
        migrations.RemoveField(
            model_name='suprafete',
            name='utila',
        ),
        migrations.AddField(
            model_name='construction',
            name='totala',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='construction',
            name='utila',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
