# Generated by Django 3.2.6 on 2021-11-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0016_alter_presentationdata_access_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketanalysis',
            name='range',
        ),
    ]
