# Generated by Django 3.2.6 on 2021-10-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0017_auto_20211022_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuationsummary',
            name='boxa_iv',
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='boxa_mv',
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='subteran_iv',
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='subteran_mv',
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='suprateran_iv',
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='suprateran_mv',
        ),
        migrations.CreateModel(
            name='SummaryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=55, null=True)),
                ('field_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approache', models.CharField(blank=True, max_length=55, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.valuationsummary')),
            ],
        ),
    ]
