# Generated by Django 3.2.6 on 2021-11-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0018_auto_20211123_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_to', models.CharField(blank=True, max_length=10, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='PropertyFiels/%Y/%m/%d')),
                ('comp_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.comparableproperty')),
            ],
        ),
    ]
