# Generated by Django 3.2.6 on 2021-10-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0018_auto_20211026_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparableproperty',
            name='price_persqm',
        ),
        migrations.RemoveField(
            model_name='comparableproperty',
            name='rent_sqm',
        ),
        migrations.AddField(
            model_name='comparabletable',
            name='price_persqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suprafete',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MvbTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_rent_sqm', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_monthly_rent', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_vbp', models.CharField(blank=True, max_length=10, null=True)),
                ('vpcd', models.CharField(blank=True, max_length=10, null=True)),
                ('vpcd_rotund', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_rent', models.CharField(blank=True, max_length=50, null=True)),
                ('rent_sqm', models.CharField(blank=True, max_length=50, null=True)),
                ('vbp', models.CharField(blank=True, max_length=50, null=True)),
                ('mvbp', models.CharField(blank=True, max_length=50, null=True)),
                ('min_mvbp', models.CharField(blank=True, max_length=10, null=True)),
                ('ref_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.valuatedproperty')),
            ],
        ),
    ]
