# Generated by Django 3.2.6 on 2021-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0019_auto_20211029_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='suprafete',
            name='is_utila',
            field=models.BooleanField(default=1),
        ),
    ]
