# Generated by Django 3.2.6 on 2021-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0019_propertyfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='interior_finishes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationdata',
            name='current_use_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationdata',
            name='inspectia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valuationsummary',
            name='purpose_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='zona_type',
            field=models.CharField(blank=True, choices=[('1', 'Medii sau sub medie, de varsta medie'), ('2', 'Medii sau peste medie, de varsta medie')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='current_use',
            field=models.CharField(blank=True, choices=[('liber', 'Liber'), ('locuit de proprietar', 'locuit de proprietar'), ('locuit de chirias', 'locuit de chirias')], max_length=155, null=True),
        ),
    ]
