# Generated by Django 3.2.6 on 2021-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0020_auto_20211203_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryvalue',
            name='approache',
        ),
        migrations.RemoveField(
            model_name='valuationsummary',
            name='approach',
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='current_use',
            field=models.CharField(blank=True, choices=[('liber', 'liber'), ('locuit de proprietar', 'locuit de proprietar'), ('locuit de chirias', 'locuit de chirias')], max_length=155, null=True),
        ),
    ]
